"""hg-mcp tools package.

Exports all Mercurial MCP tools organized by category.
"""

# Import mcp server first to avoid circular imports
from hg_mcp.server import mcp  # noqa: F401

# Import all tools to register them with the MCP server
# Tools are automatically registered when their modules are imported
from hg_mcp.tools.branching import (
    hg_bookmark,
    hg_bookmarks,
    hg_branch,
    hg_config,
    hg_extensions,
    hg_paths,
    hg_phases,
    hg_pull,
    hg_push,
    hg_tag,
    hg_tags,
    hg_topic,
    hg_topic_current,
    hg_topics,
)
from hg_mcp.tools.core import (
    hg_add,
    hg_amend,
    hg_cat,
    hg_clone,
    hg_commit,
    hg_diff,
    hg_init,
    hg_log,
    hg_remove,
    hg_rename,
    hg_revert,
    hg_shelve,
    hg_status,
    hg_unshelve,
    hg_update,
)
from hg_mcp.tools.hggit import (
    hg_absorb,
    hg_evolve,
    hg_fold,
    hg_git,
    hg_metaedit,
    hg_next,
    hg_previous,
    hg_prune,
    hg_rebase,
    hg_rewind,
    hg_split,
    hg_stack,
    hg_strip,
    hg_transplant,
    hg_uncommit,
)
from hg_mcp.tools.history import (
    hg_annotate,
    hg_backout,
    hg_bisect,
    hg_export,
    hg_files,
    hg_heads,
    hg_help,
    hg_histedit,
    hg_identify,
    hg_import,
    hg_incoming,
    hg_largefiles,
    hg_outgoing,
    hg_summary,
    hg_verify,
)
from hg_mcp.tools.merge import hg_graft, hg_merge, hg_resolve

__all__ = [
    "hg_absorb",
    "hg_add",
    "hg_amend",
    "hg_annotate",
    "hg_backout",
    "hg_bisect",
    "hg_bookmark",
    "hg_bookmarks",
    "hg_branch",
    "hg_cat",
    "hg_clone",
    "hg_commit",
    "hg_config",
    "hg_diff",
    "hg_evolve",
    "hg_export",
    "hg_extensions",
    "hg_files",
    "hg_fold",
    "hg_git",
    "hg_graft",
    "hg_heads",
    "hg_help",
    "hg_histedit",
    "hg_identify",
    "hg_import",
    "hg_incoming",
    "hg_init",
    "hg_largefiles",
    "hg_log",
    "hg_merge",
    "hg_metaedit",
    "hg_next",
    "hg_outgoing",
    "hg_paths",
    "hg_phases",
    "hg_previous",
    "hg_prune",
    "hg_pull",
    "hg_push",
    "hg_rebase",
    "hg_remove",
    "hg_rename",
    "hg_resolve",
    "hg_revert",
    "hg_rewind",
    "hg_shelve",
    "hg_split",
    "hg_stack",
    "hg_status",
    "hg_strip",
    "hg_summary",
    "hg_tag",
    "hg_tags",
    "hg_topic",
    "hg_topic_current",
    "hg_topics",
    "hg_transplant",
    "hg_uncommit",
    "hg_unshelve",
    "hg_update",
    "hg_verify",
]
